# -*- coding: utf-8 -*-
"""Delhi_Air_Quality data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8CKgXnrED7e3qc7xRguYUDI5a68DxYc
"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as f
spark = SparkSession.builder.appName("Delhi Air Quality").getOrCreate()

"""**LOADING THE DATA **"""

df= spark.read.csv("/content/Delhi Air Quality Time Series Dataset.csv",header=True,inferSchema= True)

"""1. Display First 20 Records
Understand dataset structure.
**bold text**
"""

df.show(20)

"""2. Print Dataset Schema
**bold text**
"""

df.printSchema()

"""3. Count Total Air Quality Records

"""

df.count()

"""4. Select Important Columns
Objective

Work only with required columns.

Task

Display:

Locations
Parameters
Values

only.

"""

df.select("Locations","Parameters","Values").show(5)

"""5.Find Highly Polluted Readings
Objective

Pollution alert analysis.

Task

Display records where:

Values > 300

"""

df.filter(f.col("Values")>300).show(10)

"""6.Find Unique Pollution Parameters
Objective

Understand pollutants monitored.

Task

Find all unique pollution parameters.

Example:

no
no2
pm2.5
co

"""

df.select("Parameters").distinct().show()

"""7.Find Top 10 Highest Pollution Readings
Objective

Critical pollution analysis.

Task

Display top 10 highest pollution values.

"""

df.orderBy(f.col("Values").desc()).show(10)

"""8.Find Pollution Readings During Night Hours
Objective

Time-based analysis.

Task

Display records where:

hour > 20

"""

df.filter(f.col("hour")>20).show()

"""9.Find Average Pollution by Location
Objective

City pollution comparison.

Task

Calculate average pollution value for each location.

"""

df.groupBy("Locations").mean("Values").show()

"""10.Find Maximum Pollution Per Parameter
Objective

Identify most dangerous pollutants.

Task

Find highest recorded value for each pollutant.

"""

df.groupby("Parameters").max("Values").show()

"""11.Count Records Per Location
Objective

Sensor activity analysis.

Task

Find number of pollution records collected from each location.

"""

df.groupBy("Locations").count().show()

"""12.Add Pollution Severity Category
Objective

Environmental risk classification.

Task

Create:

pollution_level

Conditions:

High → Values > 300
Medium → 100 to 300
Low → below 100
"""

from pyspark.sql.functions import when
df.withColumn("Pollution_level",
              when(df["Values"]>300,"High")
              .when((df["Values"]>=100 )& (df["Values"] <=300), "Medium")
              .otherwise("Low")
).show()

"""13.Find Most Polluted Locations
Objective

Environmental hotspot analysis.

Task

Find locations with highest total pollution readings.

"""

df.groupBy("Locations").max("Values").show()

"""14.Find Pollution Trend Hour-wise
Objective

Time-series analysis.

Task

Calculate average pollution for each hour.

"""

df.groupBy("hour").mean("Values").orderBy("hour").show()

"""15.Rename Column
Objective

Improve dataset readability.

Task

Rename:

Values

to:

pollution_value

"""

df.withColumnRenamed("Values", "pollution_values").show()

"""16.Remove Duplicate Records
Objective

Data cleaning.

Task

Remove duplicate pollution records.

"""

df.drop_duplicates().show()

"""17.Generate Statistical Summary
Objective

Quick pollution analytics.

Task

Generate statistical summary for:

Values

"""

df.columns

df.select("Values").describe().show()

"""18.Find Pollution Readings for Specific Pollutant
Objective

Pollutant-specific analysis.

Task

Display all:

pm2.5

records only.

"""

df.filter(f.col("Parameters")=="pm25").show()

"""19.Save Highly Polluted Records
Objective

Industry ETL workflow.

Task

Save records where:

Values > 300

into new CSV file.

"""

high_polluted_records= df.filter(f.col("Values")>300)

high_polluted_records.write.csv("High polluted records", header=True, mode="overwrite")

"""20.Create Environmental Monitoring Dashboard Dataset
Objective

Industry-level reporting.

Task

Generate location-wise report containing:

Average pollution
Maximum pollution
Total records
"""

from pyspark.sql.functions import avg,count,max,round
location_report = df.groupBy("Locations").agg(round(avg("Values"),2).alias("Average Pollution"),max("Values").alias("Maximum Pollution"),count("*").alias("Total Records")).show()

